services:
  aiparticipant:
    build: .

    environment:
      SPRING_AI_OLLAMA_BASE_URL: ${SPRING_AI_OLLAMA_BASE_URL}
      SPRING_AI_OLLAMA_CHAT_MODEL: ${SPRING_AI_OLLAMA_CHAT_MODEL}
      SPRING_AI_OLLAMA_CHAT_KEEP_ALIVE: ${SPRING_AI_OLLAMA_CHAT_KEEP_ALIVE}
      SPRING_AI_OLLAMA_CHAT_NUM_CTX: ${SPRING_AI_OLLAMA_CHAT_NUM_CTX}

      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN:?}
      DISCORD_MESSAGE_HISTORY_SIZE: ${DISCORD_MESSAGE_HISTORY_SIZE}
